In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#tf.debugging.set_log_device_placement(True)

In [3]:
tf.executing_eagerly()

True

In [4]:
#tensors are usually a multi deimensional array but it can hold scalar values as well
x0 = tf.constant(3)
x0.dtype #print out datatype

tf.int32

In [5]:
x1= tf.constant([1.1,1.2,1.3,1.4])
x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 1.2, 1.3, 1.4], dtype=float32)>

In [6]:
result1=x1+5
result1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 6.2, 6.3, 6.4], dtype=float32)>

In [7]:
result1 = tf.add(x1,tf.constant(5.0))
result1
#tensors are immutable

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 6.2, 6.3, 6.4], dtype=float32)>

In [8]:
x2= tf.constant([[ 1,2,3,4],[5,6,7,8]])
x2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [9]:
#casting to another data type
x2= tf.cast(x2,tf.float32)
x2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [10]:
arr1 = x1.numpy()
arr1
#converting it to numpy

array([1.1, 1.2, 1.3, 1.4], dtype=float32)

In [11]:
x4 = tf.convert_to_tensor(arr1)
x4

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 1.2, 1.3, 1.4], dtype=float32)>

In [12]:
# we can perform numpy operations on tensors but not recommended 
#to check if a variable is a tensor
tf.is_tensor(x1)

True

In [13]:
#creating tensor with all zero values and defining the shape and datatype
t0 = tf.zeros([3,5],tf.int32)
t0

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [14]:
#creating tensor with all ones values and defining the shape and datatype
t1 = tf.ones([3,5],tf.int32)
t1

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [15]:
# we can reshape the tensor. the rehspae dimension should match 
t0_reshape = tf.reshape(t0,[5,3])
t0_reshape

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [16]:
#Variables
#variables are recommended way to share persistent state in your tensorflow programs. They are mutable. A tensorflow vairable 
# cane be thought as a mutable container holding tensors.tensors held by a variable can be mutated or changed by running operations

In [17]:
v1 = tf.Variable([[1.5,2,5],[2,6,7]])
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)>

In [18]:
v2 = tf.Variable([[1.5,2,5],[2,6,7]],dtype=tf.float32)
v2

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)>

In [19]:
tf.add(v1,v2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3.,  4., 10.],
       [ 4., 12., 14.]], dtype=float32)>

In [20]:
tf.convert_to_tensor(v1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)>

In [21]:
v1.numpy()

array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)

In [22]:

#immutable thus we can change
v1.assign([[19,20,30],[20,43,76]])
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[19., 20., 30.],
       [20., 43., 76.]], dtype=float32)>

In [23]:
v1.assign_add([[19,20,30],[20,43,76]])
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 38.,  40.,  60.],
       [ 40.,  86., 152.]], dtype=float32)>

In [24]:
v1.assign_sub([[19,20,30],[20,43,76]])
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[19., 20., 30.],
       [20., 43., 76.]], dtype=float32)>

In [25]:
var_a =tf.Variable([2.0,3.0])
var_a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [26]:
var_b =tf.Variable(var_a)
var_a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

## Functions

In [27]:
#Decorate functions with tf.function
#Functions can be faster than eager code, especially for
#graphs with many small ops. But for graphs with a few expensive 
#ops (like convolutions), you may not see much speedup.

@tf.function
def add(a, b):
    return a + b

@tf.function
def sub(a, b):
    return a - b

@tf.function
def mul(a, b):
    return a * b

@tf.function
def div(a, b):
    return a / b


print(add(tf.constant(5), tf.constant(2)))
print(sub(tf.constant(5), tf.constant(2)))
print(mul(tf.constant(5), tf.constant(2)))
print(div(tf.constant(5), tf.constant(2)))

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(2.5, shape=(), dtype=float64)


## Creating Random Tensors

In [36]:
random_1= tf.random.Generator.from_seed(7) #set seed for reproducibility 
random_1 = random_1.normal(shape=[2,3])
print(random_1)

random_2 =tf.random.Generator.from_seed(7) #set seed for reproducibility 
random_2= random_2.uniform(shape=[2,3])
print(random_2)

tf.Tensor(
[[-1.3240396   0.28785667 -0.8757901 ]
 [-0.08857018  0.69211644  0.84215707]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.39932835 0.7840713  0.67880154]
 [0.73395896 0.5520444  0.10948515]], shape=(2, 3), dtype=float32)
