In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.debugging.set_log_device_placement(True)

In [4]:
tf.executing_eagerly()

True

In [6]:
#tensors are usually a multi deimensional array but it can hold scalar values as well
x0 = tf.constant(3)
x0.dtype #print out datatype

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [8]:
x1= tf.constant([1.1,1.2,1.3,1.4])
x1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 1.2, 1.3, 1.4], dtype=float32)>

In [9]:
result1=x1+5
result1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 6.2, 6.3, 6.4], dtype=float32)>

In [12]:
result1 = tf.add(x1,tf.constant(5.0))
result1
#tensors are immutable

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 6.2, 6.3, 6.4], dtype=float32)>

In [14]:
x2= tf.constant([[ 1,2,3,4],[5,6,7,8]])
x2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [17]:
#casting to another data type
x2= tf.cast(x2,tf.float32)
x2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [18]:
arr1 = x1.numpy()
arr1
#converting it to numpy

array([1.1, 1.2, 1.3, 1.4], dtype=float32)

In [19]:
x4 = tf.convert_to_tensor(arr1)
x4

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 1.2, 1.3, 1.4], dtype=float32)>

In [20]:
# we can perform numpy operations on tensors but not recommended 
#to check if a variable is a tensor
tf.is_tensor(x1)

True

In [22]:
#creating tensor with all zero values and defining the shape and datatype
t0 = tf.zeros([3,5],tf.int32)
t0

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [23]:
#creating tensor with all ones values and defining the shape and datatype
t1 = tf.ones([3,5],tf.int32)
t1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [25]:
# we can reshape the tensor. the rehspae dimension should match 
t0_reshape = tf.reshape(t0,[5,3])
t0_reshape

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [26]:
#Variables
#variables are recommended way to share persistent state in your tensorflow programs. They are mutable. A tensorflow vairable 
# cane be thought as a mutable container holding tensors.tensors held by a variable can be mutated or changed by running operations

In [28]:
v1 = tf.Variable([[1.5,2,5],[2,6,7]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)>

In [30]:
v2 = tf.Variable([[1.5,2,5],[2,6,7]],dtype=tf.float32)
v2

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)>

In [31]:
tf.add(v1,v2)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3.,  4., 10.],
       [ 4., 12., 14.]], dtype=float32)>

In [33]:
tf.convert_to_tensor(v1)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)>

In [34]:
v1.numpy()

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)

In [37]:

#immutable thus we can change
v1.assign([[19,20,30],[20,43,76]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[19., 20., 30.],
       [20., 43., 76.]], dtype=float32)>

In [38]:
v1.assign_add([[19,20,30],[20,43,76]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignAddVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 38.,  40.,  60.],
       [ 40.,  86., 152.]], dtype=float32)>

In [39]:
v1.assign_sub([[19,20,30],[20,43,76]])
v1

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignSubVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[19., 20., 30.],
       [20., 43., 76.]], dtype=float32)>

In [41]:
var_a =tf.Variable([2.0,3.0])
var_a

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [43]:
var_b =tf.Variable(var_a)
var_a

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>