In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#tf.debugging.set_log_device_placement(True)

In [3]:
tf.executing_eagerly()

True

In [4]:
#tensors are usually a multi deimensional array but it can hold scalar values as well
x0 = tf.constant(3)
x0.dtype #print out datatype

tf.int32

In [5]:
x1= tf.constant([1.1,1.2,1.3,1.4])
x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 1.2, 1.3, 1.4], dtype=float32)>

In [6]:
result1=x1+5
result1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 6.2, 6.3, 6.4], dtype=float32)>

In [7]:
result1 = tf.add(x1,tf.constant(5.0))
result1
#tensors are immutable

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 6.2, 6.3, 6.4], dtype=float32)>

In [8]:
x2= tf.constant([[ 1,2,3,4],[5,6,7,8]])
x2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [9]:
#casting to another data type
x2= tf.cast(x2,tf.float32)
x2

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [10]:
arr1 = x1.numpy()
arr1
#converting it to numpy

array([1.1, 1.2, 1.3, 1.4], dtype=float32)

In [11]:
x4 = tf.convert_to_tensor(arr1)
x4

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 1.2, 1.3, 1.4], dtype=float32)>

In [12]:
# we can perform numpy operations on tensors but not recommended 
#to check if a variable is a tensor
tf.is_tensor(x1)

True

In [13]:
#creating tensor with all zero values and defining the shape and datatype
t0 = tf.zeros([3,5],tf.int32)
t0

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [14]:
#creating tensor with all ones values and defining the shape and datatype
t1 = tf.ones([3,5],tf.int32)
t1

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [15]:
# we can reshape the tensor. the rehspae dimension should match 
t0_reshape = tf.reshape(t0,[5,3])
t0_reshape

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [16]:
#Variables
#variables are recommended way to share persistent state in your tensorflow programs. They are mutable. A tensorflow vairable 
# cane be thought as a mutable container holding tensors.tensors held by a variable can be mutated or changed by running operations

In [17]:
v1 = tf.Variable([[1.5,2,5],[2,6,7]])
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)>

In [18]:
v2 = tf.Variable([[1.5,2,5],[2,6,7]],dtype=tf.float32)
v2

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)>

In [19]:
tf.add(v1,v2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3.,  4., 10.],
       [ 4., 12., 14.]], dtype=float32)>

In [20]:
tf.convert_to_tensor(v1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)>

In [21]:
v1.numpy()

array([[1.5, 2. , 5. ],
       [2. , 6. , 7. ]], dtype=float32)

In [22]:

#immutable thus we can change
v1.assign([[19,20,30],[20,43,76]])
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[19., 20., 30.],
       [20., 43., 76.]], dtype=float32)>

In [23]:
v1.assign_add([[19,20,30],[20,43,76]])
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 38.,  40.,  60.],
       [ 40.,  86., 152.]], dtype=float32)>

In [24]:
v1.assign_sub([[19,20,30],[20,43,76]])
v1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[19., 20., 30.],
       [20., 43., 76.]], dtype=float32)>

In [25]:
var_a =tf.Variable([2.0,3.0])
var_a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [26]:
var_b =tf.Variable(var_a)
var_a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

## Functions

In [27]:
#Decorate functions with tf.function
#Functions can be faster than eager code, especially for
#graphs with many small ops. But for graphs with a few expensive 
#ops (like convolutions), you may not see much speedup.

@tf.function
def add(a, b):
    return a + b

@tf.function
def sub(a, b):
    return a - b

@tf.function
def mul(a, b):
    return a * b

@tf.function
def div(a, b):
    return a / b


print(add(tf.constant(5), tf.constant(2)))
print(sub(tf.constant(5), tf.constant(2)))
print(mul(tf.constant(5), tf.constant(2)))
print(div(tf.constant(5), tf.constant(2)))

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(2.5, shape=(), dtype=float64)


## Creating Random Tensors

In [28]:
random_1= tf.random.Generator.from_seed(7) #set seed for reproducibility 
random_1 = random_1.normal(shape=[2,3])
print(random_1)

random_2 =tf.random.Generator.from_seed(7) #set seed for reproducibility 
random_2= random_2.uniform(shape=[2,3])
print(random_2)

tf.Tensor(
[[-1.3240396   0.28785667 -0.8757901 ]
 [-0.08857018  0.69211644  0.84215707]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.39932835 0.7840713  0.67880154]
 [0.73395896 0.5520444  0.10948515]], shape=(2, 3), dtype=float32)


## shuffle tensors

In [29]:
not_shuffled = tf.constant([[10,2],[5,4],[6,2]])
print(not_shuffled)
tf.random.shuffle(not_shuffled)

tf.Tensor(
[[10  2]
 [ 5  4]
 [ 6  2]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  2],
       [ 5,  4],
       [10,  2]])>

## Numpy

One of the differences between tensors and numpy is that tensors can run on GPU

In [30]:
import numpy as np
numpy_a = np.arange(1,25,dtype =np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [31]:
#convert to tensor
a = tf.constant(numpy_a)
a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [32]:
#converting that array into a shape/dimension
b = tf.constant(numpy_a, shape=(2,3,4))
b
#the product of shape values should equal to number of elements

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

Shape: the length of each of the dimensions of a tensor
Rank: The number of tensor dimensions. A scalar has rank 0,
      vector has rank1, matrix has rank 2 and tensor has rank n(code: tensor.ndim)
Size: Total number of elements in the tensor

In [33]:
#Creating rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
print('Datatype of every element',rank_4_tensor.dtype)
print('Number of dimensions(rank)',rank_4_tensor.ndim)
print('shape of tensor', rank_4_tensor.shape)
print('Elements along 0 axis', rank_4_tensor.shape[0])
print('Elements along last axis', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor',tf.size(rank_4_tensor))
print('Total number of elements in our tensor:',tf.size(rank_4_tensor).numpy())

Datatype of every element <dtype: 'float32'>
Number of dimensions(rank) 4
shape of tensor (2, 3, 4, 5)
Elements along 0 axis 2
Elements along last axis 5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


In [35]:
#get first two elements of each dimension
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [36]:
#getting the specified shape of tensors
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
#Get first element from each dimension the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [38]:
rank_2_tensor = tf.constant([[10,2],[54,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [39]:
#Getting the last element of tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

In [40]:
#Adding an extra dimnesion to our rank / Adding new axis to the tensor
rank_3_tensor =  rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 2]],

       [[54],
        [ 4]]])>

In [41]:
#another way of adding new axis is / acis=-1 indicates that add at the end of the tensor
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 2]],

       [[54],
        [ 4]]])>

## Changing Datatypes

In [42]:
B= tf.constant([1.4,5.4])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.4, 5.4], dtype=float32)>

In [43]:
#changing datatype from float32 to float16
D= tf.cast(B,dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.4, 5.4], dtype=float16)>

## tensorflow  Aggregations

In [44]:
#absolute values of tensors
D= tf.constant([-43.3,-65.5])
print(D)
print(tf.abs(D))

tf.Tensor([-43.3 -65.5], shape=(2,), dtype=float32)
tf.Tensor([43.3 65.5], shape=(2,), dtype=float32)


In [45]:
print(tf.reduce_mean(D))#get the mean
print(tf.reduce_max(D))#get max
print(tf.reduce_min(D))#get min 
print(tf.reduce_sum(D))#get sum

tf.Tensor(-54.4, shape=(), dtype=float32)
tf.Tensor(-43.3, shape=(), dtype=float32)
tf.Tensor(-65.5, shape=(), dtype=float32)
tf.Tensor(-108.8, shape=(), dtype=float32)


In [47]:
#to find variance we need to import the tensorflow probablility library
import tensorflow_probability as tfp
tfp.stats.variance(D)

<tf.Tensor: shape=(), dtype=float32, numpy=123.21001>

In [50]:
#Getting standard deviation
tf.math.reduce_std(D)

<tf.Tensor: shape=(), dtype=float32, numpy=11.1>